spin_manifest_version = 2

[application]
name = "ai-story"
version = "0.1.0"
authors = ["Franxois <franxoois+github@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "ai-story"

[component.ai-story]
source = "target/wasm32-wasi/release/ai_story.wasm"
allowed_outbound_hosts = []
ai_models = ["llama2-chat"]

[component.ai-story.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
