spin_manifest_version = 2

[application]
name = "app-chall4"
version = "0.1.0"
authors = ["Franxois <franxoois+github@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "app-chall4"

[component.app-chall4]
source = "target/wasm32-wasi/release/app_chall4.wasm"
allowed_outbound_hosts = ["https://bulls-n-cows.fermyon.app:443"]
[component.app-chall4.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
